language:
    - cpp

env:
    - GENERATOR="-GUnix Makefiles" TOOLCHAIN=empty RUN=1

install:
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    # install cmake
    - CMAKE_VERSION="3.0.2-ios-universal"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    - cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX="`pwd`/_install/" -DCMAKE_BUILD_TYPE=Release -DCMAKE_USE_SYSTEM_CURL=YES
    - cmake --build _builds --target install
    - export PATH="`pwd`/_install/bin:${PATH}"
    - cd ..
    # -- end

script:
    - which cmake
    - cmake --version
    # Foo package install
    - cmake -HFoo-package -B_builds/Foo-debug -DCMAKE_BUILD_TYPE=Debug "${GENERATOR}" "-DCMAKE_TOOLCHAIN_FILE=`pwd`/toolchains/${TOOLCHAIN}.cmake" "-DCMAKE_INSTALL_PREFIX=`pwd`/_install"
    - cmake --build _builds/Foo-debug --target install --config Debug -- ${EXTRA}
    - cmake -HFoo-package -B_builds/Foo-release -DCMAKE_BUILD_TYPE=Release "${GENERATOR}" "-DCMAKE_TOOLCHAIN_FILE=`pwd`/toolchains/${TOOLCHAIN}.cmake" "-DCMAKE_INSTALL_PREFIX=`pwd`/_install"
    - cmake --build _builds/Foo-release --target install --config Release -- ${EXTRA}
    # -- end
    # Boo (usage Foo installed package)
    - cmake -HBoo-usage -B_builds/Boo-debug -DCMAKE_BUILD_TYPE=Debug "${GENERATOR}" "-DCMAKE_TOOLCHAIN_FILE=`pwd`/toolchains/${TOOLCHAIN}.cmake" "-DCMAKE_INSTALL_PREFIX=`pwd`/_install"
    - cmake --build _builds/Boo-debug --config Debug -- ${EXTRA}
    - cmake -HBoo-usage -B_builds/Boo-release -DCMAKE_BUILD_TYPE=Release "${GENERATOR}" "-DCMAKE_TOOLCHAIN_FILE=`pwd`/toolchains/${TOOLCHAIN}.cmake" "-DCMAKE_INSTALL_PREFIX=`pwd`/_install"
    - cmake --build _builds/Boo-release --config Release -- ${EXTRA}
    # -- end
    # Run test
    - cd _builds/Boo-debug
    - if [ "${RUN}" == "1" ]; then ctest -VV -C Debug; fi;
    - cd ../..
    - cd _builds/Boo-release
    - if [ "${RUN}" == "1" ]; then ctest -VV -C Release; fi;
    - cd ../..
    # -- end
